# Generated by Django 5.0.3 on 2024-03-24 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
        ('trainer', '0004_alter_trainer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trainer.trainer'),
        ),
    ]
