# Generated by Django 5.0.3 on 2024-04-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_module_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='trainer',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
