# Generated by Django 5.0.3 on 2024-04-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_alter_module_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='trainer',
        ),
    ]
