# Generated by Django 5.0.3 on 2024-03-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('department', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('network', 'Network')], max_length=8)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
