# Generated by Django 5.0.3 on 2024-03-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_alter_trainer_created_at_alter_trainer_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='profile',
            field=models.ImageField(null=True, upload_to='students/'),
        ),
    ]
